# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Preview text'),
        ),
    ]
